// Auto-generated by scripts/generate-site.mjs.
// Edit values here to customize this specific site without touching the template.

export interface ServicePerLang {
  slug: string;
  title: string;
  description: string;
  pageHeadline: string;
  pageContent: string;
}

export interface LocationPerLang {
  slug: string;
  pageHeadline: string;
  pageContent: string;
}

export interface Testimonial {
  quote: string;
  author: string;
}

export interface PerLangContent {
  brandName: string;
  tagline: string;
  heroHeadline: string;
  heroSubheadline: string;
  aboutPageContent: string;
  servicesIntro?: string;
  serviceAreaHeading?: string;
  seoTitle: string;
  seoDescription: string;
  primaryKeyword: string;
  testimonials: Testimonial[];
  services: ServicePerLang[];
  locations: LocationPerLang[];
}

export type Lang = "fr" | "en";

export interface SiteConfig {
  niche: string;
  city: string;
  state: string;
  domain: string;
  phone: string;
  phoneDisplay: string;
  email: string;
  address: string;
  primaryLang: Lang;
  secondaryLang?: Lang;
  heroImage?: string;
  serviceImages: (string | undefined)[];
  locationNames: string[];
  fr?: PerLangContent;
  en?: PerLangContent;
}

export const siteConfig: SiteConfig = {
  "niche": "junk removal",
  "city": "Gatineau",
  "state": "QC",
  "domain": "gatineaudebarras.com",
  "phone": "+14382566448",
  "phoneDisplay": "(438) 256-6448",
  "email": "leads@gatineaudebarras.com",
  "address": "Gatineau, QC",
  "primaryLang": "fr",
  "secondaryLang": "en",
  "heroImage": "/hero/main.png",
  "serviceImages": [
    "/hero/service-1.png",
    "/hero/service-2.png",
    "/hero/service-3.png",
    "/hero/service-4.png"
  ],
  "locationNames": [
    "Hull",
    "Aylmer",
    "Gatineau",
    "Buckingham",
    "Masson-Angers",
    "Val-des-Monts",
    "Chelsea",
    "Cantley",
    "La Pêche",
    "Templeton",
    "Pointe-Gatineau",
    "Limbour"
  ],
  "fr": {
    "brandName": "Débarras Gatineau",
    "tagline": "Votre solution de débarras rapide et fiable",
    "heroHeadline": "Service de Débarras Professionnel à Gatineau",
    "heroSubheadline": "Nous enlevons vos encombrants rapidement et de manière responsable. Service courtois, prix transparents et disponibilité sept jours sur sept dans toute la région de Gatineau.",
    "aboutPageContent": "Débarras Gatineau est une entreprise locale fondée par des résidents de la région qui comprennent les besoins uniques de notre communauté. Depuis nos débuts, nous avons aidé des centaines de familles, d'entreprises et de propriétaires à reprendre le contrôle de leurs espaces en enlevant les encombrants de manière efficace et respectueuse de l'environnement.\n\nNotre mission est simple : offrir un service de débarras professionnel qui allie rapidité, transparence et responsabilité écologique. Nous croyons que chaque projet mérite une attention personnalisée, qu'il s'agisse d'un simple ramassage de meubles ou d'un débarras complet de propriété. Notre équipe formée traite chaque client avec respect et chaque bien avec soin.\n\nCe qui nous distingue, c'est notre engagement envers le recyclage et la donation. Nous ne nous contentons pas de tout jeter au dépotoir. Nous trions soigneusement les articles récupérables, nous donnons ce qui peut servir à des organismes locaux et nous recyclons les matériaux appropriés. Cette approche responsable réduit notre empreinte écologique tout en aidant notre communauté.\n\nNous desservons fièrement Hull, Aylmer, Buckingham, Masson-Angers et tous les secteurs de Gatineau. Notre flotte de camions nous permet d'intervenir rapidement, souvent le jour même. Nos prix sont établis sur place après évaluation du volume, sans frais cachés ni surprises.\n\nFaites confiance à une équipe locale qui connaît la région et qui se soucie de votre satisfaction. Contactez Débarras Gatineau dès aujourd'hui pour un service rapide, courtois et respectueux de l'environnement. Nous sommes prêts à vous aider à retrouver votre espace.",
    "servicesIntro": "Nous offrons une gamme complète de services de débarras adaptés à vos besoins spécifiques. Que vous soyez un particulier, une entreprise ou un gestionnaire immobilier, notre équipe a l'expertise pour gérer votre projet efficacement.",
    "serviceAreaHeading": "Service mobile dans toute la région",
    "seoTitle": "Débarras Gatineau | Enlèvement d'encombrants rapide",
    "seoDescription": "Service de débarras professionnel à Gatineau. Enlèvement rapide et responsable de vos encombrants. Prix transparents, disponible 7 jours. Appelez maintenant!",
    "primaryKeyword": "débarras Gatineau",
    "testimonials": [
      {
        "quote": "Service impeccable! Ils sont venus le jour même et ont tout enlevé en moins d'une heure. L'équipe était professionnelle et courtoise. Je recommande sans hésiter!",
        "author": "Marie-Claude B."
      },
      {
        "quote": "J'avais un sous-sol rempli de vieux meubles et d'objets accumulés depuis des années. Débarras Gatineau a tout enlevé rapidement et à un prix très raisonnable. Excellent travail!",
        "author": "François L."
      },
      {
        "quote": "Après la vente de la maison de mes parents, j'avais besoin d'un débarras complet. L'équipe a été respectueuse, efficace et a même donné plusieurs articles encore utilisables. Merci beaucoup!",
        "author": "Isabelle D."
      }
    ],
    "services": [
      {
        "slug": "debarras-residentiel",
        "title": "Débarras Résidentiel",
        "description": "Nous enlevons meubles, électroménagers, matelas et tous types d'encombrants de votre maison, appartement ou condo. Service rapide avec nettoyage après enlèvement inclus.",
        "pageHeadline": "Service de Débarras Résidentiel à Gatineau",
        "pageContent": "Votre maison mérite un espace dégagé et fonctionnel. Notre service de débarras résidentiel est conçu pour vous aider à reprendre le contrôle de votre espace de vie en enlevant rapidement tous les encombrants qui s'accumulent au fil du temps. Que vous rénoviez, déménagiez ou simplement fassiez le grand ménage, nous sommes là pour vous.\n\nNous enlevons tous types d'articles résidentiels : vieux meubles, électroménagers désuets, matelas et sommiers, appareils électroniques, équipement de sport, jouets, décoration, et bien plus encore. Notre équipe expérimentée sait manipuler les objets lourds et volumineux en toute sécurité, sans endommager vos murs, planchers ou cadres de porte.\n\nNotre processus est simple et sans tracas. Vous nous montrez ce qui doit partir, nous vous donnons un prix fixe sur place, et si vous acceptez, nous chargeons tout immédiatement. Pas besoin de descendre vos items au rez-de-chaussée – nous nous occupons de tout, peu importe l'étage. Nous balayons même la zone après le chargement.\n\nNous comprenons que certains objets ont une valeur sentimentale ou peuvent encore servir. C'est pourquoi nous trions soigneusement ce que nous ramassons. Les meubles et articles en bon état sont donnés à des organismes de charité locaux. Les matériaux recyclables sont acheminés vers les centres appropriés. Seulement ce qui ne peut être récupéré est envoyé au site d'enfouissement.\n\nDisponibles sept jours sur sept dans tous les secteurs de Gatineau, nous offrons souvent un service le jour même. Nos prix sont parmi les plus compétitifs de la région, calculés selon le volume réel occupé dans notre camion. Contactez-nous dès maintenant pour libérer votre espace de vie et retrouver la tranquillité d'esprit que vous méritez."
      },
      {
        "slug": "debarras-commercial",
        "title": "Débarras Commercial et Industriel",
        "description": "Enlèvement d'équipement de bureau, mobilier commercial, inventaire excédentaire et rebuts industriels. Service discret adapté aux horaires d'entreprise.",
        "pageHeadline": "Débarras Commercial et Industriel à Gatineau",
        "pageContent": "Les entreprises de Gatineau font confiance à Débarras Gatineau pour gérer l'enlèvement de leurs encombrants commerciaux et industriels. Nous comprenons que votre temps est précieux et que les interruptions d'activité doivent être minimisées. C'est pourquoi nous offrons un service flexible, rapide et professionnel adapté aux besoins des commerces.\n\nNous enlevons tout type d'équipement commercial : mobilier de bureau désuet, classeurs et bureaux, chaises de conférence, équipement informatique et électronique, rayonnages et étagères, inventaire périmé, machinerie industrielle, palettes et matériel d'emballage. Aucun projet n'est trop grand ou trop petit pour notre équipe.\n\nNotre service s'adapte à vos horaires d'exploitation. Nous pouvons intervenir en soirée, les fins de semaine ou pendant vos heures creuses pour ne pas perturber vos opérations. Pour les projets d'envergure, nous planifions le travail par phases selon vos besoins. Notre équipe travaille de manière discrète et efficace, en respectant vos employés et vos clients.\n\nLa confidentialité et la sécurité sont nos priorités. Si vous avez des documents sensibles ou de l'équipement contenant des données, nous pouvons coordonner avec des services de destruction sécurisée. Nous comprenons également les exigences de conformité environnementale et nous assurons que tous les matériaux sont disposés selon les règlements en vigueur.\n\nNous offrons des tarifs commerciaux compétitifs avec facturation claire et professionnelle. Pour les contrats récurrents ou les grands projets, nous proposons des prix préférentiels. Demandez une soumission gratuite dès aujourd'hui et découvrez pourquoi tant d'entreprises de Gatineau choisissent nos services pour leurs besoins de débarras commercial."
      },
      {
        "slug": "debarras-renovation",
        "title": "Débarras de Rénovation et Construction",
        "description": "Enlèvement de débris de construction, matériaux de démolition, vieux revêtements et résidus de chantier. Intervention rapide pour garder votre projet sur la bonne voie.",
        "pageHeadline": "Débarras de Rénovation et Débris de Construction",
        "pageContent": "Les projets de rénovation génèrent rapidement une quantité importante de débris et de matériaux encombrants. Notre service de débarras de rénovation et construction est spécialement conçu pour les entrepreneurs, les rénovateurs et les propriétaires qui ont besoin d'enlever rapidement les résidus de chantier pour maintenir l'avancement de leurs travaux.\n\nNous enlevons tous types de débris de construction : gypse et placoplatre, bois de charpente et moulures, portes et fenêtres, armoires de cuisine, comptoirs, tuiles et céramique, tapis et sous-plancher, bardeaux d'asphalte, revêtements extérieurs, isolant, fils et tuyauterie. Notre équipe connaît bien les matériaux de construction et sait comment les manipuler en toute sécurité.\n\nPour les entrepreneurs et les équipes de rénovation, nous offrons un service flexible qui s'intègre à votre calendrier de projet. Nous pouvons planifier des ramassages réguliers pendant la durée de vos travaux ou intervenir ponctuellement selon l'accumulation de débris. Notre rapidité d'intervention vous permet de garder le chantier propre et sécuritaire.\n\nNous respectons les normes environnementales en triant les matériaux recyclables comme le métal, le bois non traité et certains types de plastique. Cette approche responsable réduit la quantité de débris envoyée aux sites d'enfouissement tout en vous aidant à respecter les exigences environnementales de votre projet.\n\nNos camions peuvent accéder à la plupart des chantiers résidentiels et commerciaux dans la région de Gatineau. Nous offrons des prix compétitifs basés sur le volume et le type de matériaux. Pour les projets d'envergure, nous pouvons fournir une soumission détaillée. Contactez-nous pour discuter de votre projet de rénovation et découvrir comment nous pouvons faciliter votre chantier."
      },
      {
        "slug": "debarras-succession",
        "title": "Débarras de Succession et Liquidation",
        "description": "Service complet et respectueux pour vider une propriété suite à un décès ou une liquidation. Nous traitons chaque situation avec compassion et professionnalisme.",
        "pageHeadline": "Débarras de Succession et Liquidation de Propriété",
        "pageContent": "Vider une maison suite à un décès ou préparer une propriété pour la vente est une tâche émotionnellement difficile. Notre service de débarras de succession est offert avec compassion, respect et professionnalisme. Nous comprenons la sensibilité de ces situations et nous travaillons avec délicatesse pour vous aider à traverser cette étape difficile.\n\nNous offrons un service complet de liquidation de propriété qui inclut l'enlèvement de tous les biens : meubles, vêtements, vaisselle, livres, décorations, appareils électroniques, articles de jardin et tout ce qui se trouve dans la résidence. Nous pouvons vider une maison complète en une seule journée ou travailler progressivement selon votre rythme et vos besoins émotionnels.\n\nNotre approche est respectueuse et méthodique. Si vous souhaitez conserver certains objets ou documents importants, nous prenons le temps de trier avec vous avant de commencer. Nous manipulons chaque article avec soin, conscients que même les objets ordinaires peuvent avoir une signification particulière. Notre équipe est formée pour travailler avec empathie dans ces circonstances délicates.\n\nNous maximisons la valeur de la succession en identifiant les articles qui peuvent être donnés à des organismes de charité, générant ainsi des reçus fiscaux pour la succession. Les meubles et objets en bon état sont offerts à des familles dans le besoin plutôt que d'être simplement jetés. Cette approche honore la mémoire du défunt en donnant une seconde vie à ses possessions.\n\nNous travaillons souvent en collaboration avec des notaires, des exécuteurs testamentaires et des agents immobiliers pour coordonner le débarras selon les échéanciers de vente ou de transfert de propriété. Nos services sont disponibles dans toute la région de Gatineau. Contactez-nous pour discuter de votre situation en toute confidentialité et obtenir un accompagnement respectueux durant cette période difficile."
      }
    ],
    "locations": [
      {
        "slug": "debarras-hull",
        "pageHeadline": "Service de Débarras à Hull",
        "pageContent": "Hull est l'un des secteurs les plus dynamiques de Gatineau, avec ses quartiers résidentiels établis et son centre-ville en pleine transformation. Débarras Gatineau offre un service rapide et fiable à tous les résidents et commerces de Hull qui ont besoin d'enlever des encombrants.\n\nNous connaissons bien les particularités de Hull, de ses maisons centenaires du Vieux-Hull aux condos modernes près du Casino. Nos camions naviguent facilement dans les rues étroites du quartier historique et nous avons l'expérience nécessaire pour manipuler des objets lourds dans les escaliers étroits typiques des bâtiments plus anciens.\n\nQue vous rénoviez une propriété patrimoniale, déménagiez d'un appartement sur la rue Laurier ou liquidiez une succession dans le secteur de Wright-Champagne, notre équipe intervient rapidement. Nous offrons souvent un service le jour même pour les urgences et nos prix restent parmi les plus compétitifs de la région.\n\nNotre engagement envers le recyclage et la donation profite directement à la communauté de Hull. Les articles en bon état sont donnés à des organismes locaux qui aident les familles du secteur. Contactez-nous dès maintenant pour un service de débarras professionnel à Hull."
      },
      {
        "slug": "debarras-aylmer",
        "pageHeadline": "Service de Débarras à Aylmer",
        "pageContent": "Aylmer combine le charme d'un village historique avec des développements résidentiels modernes, créant une communauté diversifiée qui s'étend du Vieux-Aylmer jusqu'aux nouveaux quartiers. Débarras Gatineau dessert fièrement toute la région d'Aylmer avec un service de débarras adapté aux besoins uniques de ce secteur.\n\nNous intervenons dans tous les quartiers d'Aylmer, des propriétés riveraines luxueuses du bord de la rivière des Outaouais aux maisons familiales des développements Plateau, Champlain et Wychwood. Notre équipe connaît bien les accès parfois difficiles de certaines propriétés et nous sommes équipés pour gérer tous les types de situations.\n\nLes résidents d'Aylmer apprécient notre rapidité d'intervention et notre approche respectueuse de l'environnement. Que vous ayez besoin d'enlever de vieux meubles de patio avant l'hiver, de vider un garage rempli d'équipement sportif ou de débarrasser une propriété complète, nous offrons un service courtois et efficace à prix transparent.\n\nDisponibles sept jours sur sept, nous pouvons souvent intervenir le jour même de votre appel. Notre connaissance du secteur d'Aylmer nous permet de planifier nos déplacements efficacement et de vous offrir un service rapide. Appelez-nous aujourd'hui pour découvrir pourquoi tant de résidents d'Aylmer nous font confiance."
      },
      {
        "slug": "debarras-gatineau",
        "pageHeadline": "Service de Débarras dans le Secteur Gatineau",
        "pageContent": "Le secteur Gatineau, avec ses quartiers établis et ses artères commerciales animées, représente le cœur de notre ville. Débarras Gatineau est fier d'offrir un service local de débarras à tous les résidents et entreprises de ce secteur dynamique.\n\nDu boulevard Maloney au secteur de Pointe-Gatineau, en passant par les quartiers résidentiels autour du boulevard de l'Hôpital, nous connaissons chaque recoin du secteur Gatineau. Notre équipe intervient rapidement dans les maisons unifamiliales, les immeubles à logements et les commerces locaux qui ont besoin d'enlever des encombrants.\n\nNous comprenons les défis particuliers du secteur Gatineau : stationnement limité dans certains quartiers, accès aux étages supérieurs des plex, et volume important de débarras lors des périodes de déménagement. Notre expérience locale nous permet de gérer ces situations efficacement tout en respectant votre propriété et vos voisins.\n\nNotre service s'adapte à vos besoins, qu'il s'agisse d'un simple ramassage de quelques articles ou d'un débarras complet de propriété. Nous offrons des prix transparents établis sur place et nous travaillons rapidement pour minimiser les désagréments. Contactez Débarras Gatineau dès maintenant pour un service professionnel dans votre secteur."
      },
      {
        "slug": "debarras-buckingham",
        "pageHeadline": "Service de Débarras à Buckingham",
        "pageContent": "Buckingham, avec son caractère distinct et sa forte identité communautaire, mérite un service de débarras qui comprend ses particularités. Débarras Gatineau offre un service fiable et rapide à tous les résidents de Buckingham et des environs.\n\nNous desservons tout le secteur de Buckingham, du centre-ville historique aux quartiers résidentiels en expansion. Notre équipe connaît bien les routes de campagne et les chemins privés qui mènent à de nombreuses propriétés du secteur. Nous sommes équipés pour accéder aux résidences plus isolées et aux terrains de grande superficie.\n\nLes propriétaires de Buckingham accumulent souvent des équipements saisonniers, du matériel de ferme ou d'aménagement paysager, et des objets volumineux dans leurs garages et remises. Notre service de débarras est parfait pour libérer ces espaces et vous permettre de mieux profiter de votre propriété. Nous enlevons tout, des vieux meubles aux équipements lourds.\n\nNotre engagement envers un service rapide signifie que nous pouvons souvent intervenir dans les 24 heures suivant votre appel. Nos prix restent compétitifs malgré la distance, et nous offrons toujours une évaluation gratuite sur place. Faites confiance à une équipe locale qui connaît Buckingham et qui se soucie de votre satisfaction."
      },
      {
        "slug": "debarras-masson-angers",
        "pageHeadline": "Service de Débarras à Masson-Angers",
        "pageContent": "Masson-Angers est un secteur en pleine croissance qui combine des quartiers établis avec de nouveaux développements résidentiels. Débarras Gatineau est fier d'offrir un service de débarras professionnel à toute la communauté de Masson-Angers.\n\nNous intervenons dans tous les quartiers de Masson-Angers, des propriétés riveraines le long de la rivière des Outaouais aux nouveaux développements domiciliaires. Notre équipe comprend les besoins des jeunes familles qui s'installent dans le secteur ainsi que des résidents de longue date qui souhaitent désencombrer leurs espaces.\n\nQue vous ayez besoin d'enlever de vieux meubles lors d'un déménagement, de vider un sous-sol rempli d'objets accumulés ou de débarrasser des débris de rénovation, nous offrons un service rapide et courtois. Notre approche respectueuse de l'environnement signifie que nous recyclons et donnons autant que possible plutôt que de tout envoyer au dépotoir.\n\nDisponibles sept jours sur sept, nous offrons une flexibilité d'horaire qui convient aux familles occupées de Masson-Angers. Nos prix sont transparents et établis sur place après évaluation du volume. Contactez-nous dès aujourd'hui pour un service de débarras qui respecte votre temps et votre budget."
      },
      {
        "slug": "debarras-val-des-monts",
        "pageHeadline": "Service de Débarras à Val-des-Monts",
        "pageContent": "Val-des-Monts, avec ses lacs magnifiques et ses propriétés spacieuses, présente des défis uniques pour le débarras. Débarras Gatineau offre un service adapté aux besoins particuliers de cette municipalité rurale située à proximité de Gatineau.\n\nNous desservons tous les secteurs de Val-des-Monts, incluant Perkins, Saint-Pierre-de-Wakefield et les nombreux hameaux dispersés dans la municipalité. Notre équipe a l'habitude de naviguer sur les chemins de campagne et d'accéder aux propriétés situées en retrait des routes principales.\n\nLes résidents de Val-des-Monts ont souvent des chalets, des garages et des remises remplis d'équipement saisonnier, de vieux meubles et d'objets accumulés au fil des ans. Notre service de débarras vous aide à libérer ces espaces précieux. Nous enlevons tout type d'encombrants, des électroménagers aux matériaux de construction, en passant par les meubles de patio et l'équipement nautique.\n\nMalgré la distance, nous offrons des tarifs compétitifs et un service rapide. Nous planifions nos déplacements à Val-des-Monts de manière efficace pour vous offrir le meilleur prix possible. Notre engagement envers le recyclage et la donation s'applique également aux articles que nous ramassons dans votre secteur. Appelez-nous pour discuter de vos besoins de débarras à Val-des-Monts."
      },
      {
        "slug": "debarras-chelsea",
        "pageHeadline": "Service de Débarras à Chelsea",
        "pageContent": "Chelsea est reconnue pour ses magnifiques propriétés boisées et sa proximité avec le Parc de la Gatineau. Débarras Gatineau offre un service de débarras respectueux de l'environnement qui correspond aux valeurs écologiques de cette communauté unique.\n\nNous desservons tous les secteurs de Chelsea, du village principal aux propriétés situées sur les chemins Old Chelsea, Kingsmere et Scott. Notre équipe a l'expérience nécessaire pour naviguer les routes sinueuses et accéder aux propriétés en pente ou situées en forêt.\n\nLes résidents de Chelsea apprécient particulièrement notre engagement envers le recyclage et la réutilisation. Nous trions soigneusement tous les articles ramassés pour maximiser le recyclage et la donation. Cette approche responsable réduit notre impact environnemental tout en aidant des organismes locaux.\n\nQue vous rénoviez une propriété patrimoniale, déménagiez d'une maison familiale ou débarrassiez un chalet, notre service s'adapte à vos besoins. Nous offrons des horaires flexibles et pouvons souvent intervenir rapidement. Nos prix transparents et notre service courtois font de nous le choix privilégié des résidents de Chelsea pour leurs besoins de débarras."
      },
      {
        "slug": "debarras-cantley",
        "pageHeadline": "Service de Débarras à Cantley",
        "pageContent": "Cantley, avec sa combinaison unique de vie rurale et de proximité urbaine, attire de nombreuses familles qui apprécient l'espace et la nature. Débarras Gatineau offre un service de débarras adapté aux besoins spécifiques de cette municipalité en croissance.\n\nNous intervenons dans tous les secteurs de Cantley, des quartiers résidentiels près de la montée de la Source aux propriétés plus isolées le long des chemins ruraux. Notre équipe connaît bien les particularités d'accès de Cantley et nous sommes équipés pour gérer les propriétés avec de longs chemins d'entrée ou des terrains en pente.\n\nLes propriétaires de Cantley bénéficient souvent de grands terrains avec garages, remises et espaces de rangement qui peuvent s'encombrer rapidement. Notre service de débarras vous aide à récupérer ces espaces précieux en enlevant efficacement tous vos encombrants, des vieux meubles aux équipements de jardin, en passant par les matériaux de construction.\n\nNous offrons un service rapide avec possibilité d'intervention le jour même dans plusieurs cas. Nos prix sont établis de manière transparente sur place, basés sur le volume réel. Notre approche respectueuse de l'environnement assure que les articles récupérables sont recyclés ou donnés plutôt que jetés. Contactez-nous dès aujourd'hui pour un service de débarras professionnel à Cantley."
      },
      {
        "slug": "debarras-la-peche",
        "pageHeadline": "Service de Débarras à La Pêche",
        "pageContent": "La Pêche est une vaste municipalité rurale qui s'étend sur un grand territoire incluant plusieurs villages et hameaux. Débarras Gatineau offre un service de débarras fiable qui dessert toute la municipalité de La Pêche, peu importe votre localisation.\n\nNous intervenons dans tous les secteurs de La Pêche, incluant Wakefield, Alcove, Rupert, Brennan's Hill et les nombreuses propriétés dispersées dans la municipalité. Notre équipe a l'habitude des chemins de campagne et des accès parfois difficiles typiques de cette région rurale.\n\nLes propriétés de La Pêche sont souvent spacieuses avec plusieurs bâtiments secondaires où s'accumulent les objets au fil des années. Que vous ayez besoin de vider une grange, un garage, un hangar ou une maison complète, notre équipe a l'expérience et l'équipement nécessaires pour accomplir le travail efficacement.\n\nMalgré la distance et les particularités d'accès, nous offrons des tarifs compétitifs et un service professionnel. Nous planifions nos déplacements à La Pêche de manière à optimiser les coûts tout en vous offrant un service rapide. Notre engagement envers le recyclage et la donation s'étend à tous les secteurs que nous desservons. Appelez-nous pour discuter de votre projet de débarras à La Pêche."
      },
      {
        "slug": "debarras-templeton",
        "pageHeadline": "Service de Débarras à Templeton",
        "pageContent": "Templeton est un secteur dynamique de Gatineau qui combine des quartiers résidentiels établis avec des zones commerciales en développement. Débarras Gatineau offre un service de débarras complet aux résidents et aux entreprises de Templeton.\n\nNous connaissons bien tous les quartiers de Templeton, du secteur près de la montée Paiement aux développements résidentiels autour du boulevard des Allumettières. Notre équipe navigue facilement dans ce secteur et peut intervenir rapidement pour tous vos besoins de débarras.\n\nLes résidents de Templeton apprécient notre service rapide et nos prix transparents. Que vous déménagiez, rénoviez ou simplement désencombriez votre maison, nous offrons une solution efficace pour enlever tous vos articles indésirables. Nous enlevons meubles, électroménagers, matelas, équipement sportif et tout autre type d'encombrants.\n\nPour les commerces de Templeton, nous offrons également un service adapté aux horaires d'entreprise avec possibilité d'intervention en soirée ou la fin de semaine. Notre approche professionnelle et discrète respecte vos opérations tout en enlevant efficacement vos encombrants commerciaux. Contactez-nous dès maintenant pour un service de débarras professionnel à Templeton."
      },
      {
        "slug": "debarras-pointe-gatineau",
        "pageHeadline": "Service de Débarras à Pointe-Gatineau",
        "pageContent": "Pointe-Gatineau est un secteur historique de Gatineau avec une forte identité communautaire et des quartiers résidentiels bien établis. Débarras Gatineau est fier d'offrir un service de débarras local qui répond aux besoins spécifiques de ce secteur.\n\nNous desservons tous les quartiers de Pointe-Gatineau, des rues près de la rivière des Outaouais aux secteurs résidentiels autour du boulevard Saint-René. Notre équipe connaît bien les particularités du secteur, incluant les rues étroites et les maisons avec escaliers extérieurs typiques de certains quartiers.\n\nLes résidents de Pointe-Gatineau ont accès à un service de débarras rapide et fiable pour tous leurs besoins. Que vous ayez des meubles à enlever, un sous-sol à vider ou une succession à liquider, notre équipe intervient avec professionnalisme et respect. Nous manipulons vos biens avec soin et nettoyons après notre passage.\n\nNotre engagement envers la communauté se reflète dans notre approche de recyclage et de donation. Les articles en bon état sont offerts à des organismes locaux qui aident les familles de Pointe-Gatineau et des environs. Nos prix sont parmi les plus compétitifs de la région et nous offrons souvent un service le jour même. Appelez-nous pour découvrir pourquoi tant de résidents de Pointe-Gatineau nous font confiance."
      },
      {
        "slug": "debarras-limbour",
        "pageHeadline": "Service de Débarras à Limbour",
        "pageContent": "Limbour est un secteur paisible de Gatineau qui offre un cadre de vie tranquille avec de belles propriétés. Débarras Gatineau est heureux d'offrir un service de débarras professionnel aux résidents de Limbour et des environs.\n\nNous connaissons bien le secteur de Limbour et ses particularités. Notre équipe a l'habitude de naviguer dans ce secteur et peut accéder facilement aux différentes propriétés, qu'elles soient situées près des artères principales ou sur des chemins plus retirés.\n\nLes propriétaires de Limbour apprécient notre service personnalisé et notre approche respectueuse. Que vous ayez besoin d'enlever quelques articles ou de vider une propriété complète, nous offrons le même niveau de professionnalisme et d'attention. Notre équipe travaille efficacement tout en respectant votre propriété et votre tranquillité.\n\nNous offrons des horaires flexibles qui s'adaptent à votre disponibilité, incluant les soirs et les fins de semaine. Nos prix sont établis de manière transparente sur place, sans frais cachés ni surprises. Notre engagement envers le recyclage et la donation assure que vos articles sont traités de manière responsable. Contactez Débarras Gatineau dès aujourd'hui pour un service de débarras courtois et efficace à Limbour."
      }
    ]
  },
  "en": {
    "brandName": "Gatineau Junk Removal",
    "tagline": "Fast, reliable junk removal service",
    "heroHeadline": "Professional Junk Removal in Gatineau",
    "heroSubheadline": "We remove your unwanted items quickly and responsibly. Courteous service, transparent pricing, and seven-day availability throughout the Gatineau region.",
    "aboutPageContent": "Gatineau Junk Removal is a locally-owned business founded by residents who understand the unique needs of our community. Since our beginning, we've helped hundreds of families, businesses, and property owners reclaim their spaces by removing junk efficiently and in an environmentally responsible manner.\n\nOur mission is simple: to provide professional junk removal service that combines speed, transparency, and ecological responsibility. We believe every project deserves personalized attention, whether it's a simple furniture pickup or a complete property cleanout. Our trained team treats every customer with respect and every item with care.\n\nWhat sets us apart is our commitment to recycling and donation. We don't just haul everything to the landfill. We carefully sort recoverable items, donate what can still be used to local charities, and recycle appropriate materials. This responsible approach reduces our environmental footprint while helping our community.\n\nWe proudly serve Hull, Aylmer, Buckingham, Masson-Angers, and all sectors of Gatineau. Our fleet of trucks allows us to respond quickly, often same-day. Our prices are established on-site after volume assessment, with no hidden fees or surprises.\n\nTrust a local team that knows the region and cares about your satisfaction. Contact Gatineau Junk Removal today for fast, courteous, and environmentally responsible service. We're ready to help you reclaim your space.",
    "servicesIntro": "We offer a complete range of junk removal services tailored to your specific needs. Whether you're a homeowner, business, or property manager, our team has the expertise to handle your project efficiently.",
    "serviceAreaHeading": "Mobile service throughout the region",
    "seoTitle": "Gatineau Junk Removal | Fast Junk Hauling Service",
    "seoDescription": "Professional junk removal service in Gatineau. Fast and responsible removal of your unwanted items. Transparent pricing, available 7 days. Call now!",
    "primaryKeyword": "junk removal Gatineau",
    "testimonials": [
      {
        "quote": "Impeccable service! They came the same day and removed everything in less than an hour. The team was professional and courteous. I highly recommend them!",
        "author": "Sarah M."
      },
      {
        "quote": "I had a basement full of old furniture and items accumulated over years. Gatineau Junk Removal cleared everything quickly and at a very reasonable price. Excellent work!",
        "author": "Michael T."
      },
      {
        "quote": "After selling my parents' house, I needed a complete cleanout. The team was respectful, efficient, and even donated several items that were still usable. Thank you so much!",
        "author": "Jennifer K."
      }
    ],
    "services": [
      {
        "slug": "residential-junk-removal",
        "title": "Residential Junk Removal",
        "description": "We remove furniture, appliances, mattresses, and all types of household junk from your home, apartment, or condo. Fast service with post-removal cleanup included.",
        "pageHeadline": "Residential Junk Removal Service in Gatineau",
        "pageContent": "Your home deserves a clear and functional space. Our residential junk removal service is designed to help you reclaim control of your living space by quickly removing all the clutter that accumulates over time. Whether you're renovating, moving, or simply doing a major cleanup, we're here to help.\n\nWe remove all types of residential items: old furniture, outdated appliances, mattresses and box springs, electronics, sports equipment, toys, decorations, and much more. Our experienced team knows how to safely handle heavy and bulky objects without damaging your walls, floors, or door frames.\n\nOur process is simple and hassle-free. You show us what needs to go, we give you a fixed price on the spot, and if you accept, we load everything immediately. No need to bring your items down to ground level – we take care of everything, no matter what floor you're on. We even sweep the area after loading.\n\nWe understand that some items have sentimental value or can still be useful. That's why we carefully sort what we collect. Furniture and items in good condition are donated to local charities. Recyclable materials are sent to appropriate centers. Only what cannot be recovered is sent to the landfill.\n\nAvailable seven days a week in all sectors of Gatineau, we often offer same-day service. Our prices are among the most competitive in the region, calculated based on the actual volume occupied in our truck. Contact us now to free up your living space and regain the peace of mind you deserve."
      },
      {
        "slug": "commercial-junk-removal",
        "title": "Commercial and Industrial Junk Removal",
        "description": "Removal of office equipment, commercial furniture, excess inventory, and industrial waste. Discreet service adapted to business hours.",
        "pageHeadline": "Commercial and Industrial Junk Removal in Gatineau",
        "pageContent": "Gatineau businesses trust Gatineau Junk Removal to handle the removal of their commercial and industrial junk. We understand that your time is valuable and business interruptions must be minimized. That's why we offer flexible, fast, and professional service tailored to business needs.\n\nWe remove all types of commercial equipment: outdated office furniture, filing cabinets and desks, conference chairs, computer and electronic equipment, shelving and racks, expired inventory, industrial machinery, pallets and packaging materials. No project is too large or too small for our team.\n\nOur service adapts to your operating hours. We can work evenings, weekends, or during your slow periods to avoid disrupting your operations. For large projects, we plan the work in phases according to your needs. Our team works discreetly and efficiently, respecting your employees and customers.\n\nConfidentiality and security are our priorities. If you have sensitive documents or equipment containing data, we can coordinate with secure destruction services. We also understand environmental compliance requirements and ensure all materials are disposed of according to current regulations.\n\nWe offer competitive commercial rates with clear and professional invoicing. For recurring contracts or large projects, we propose preferential pricing. Request a free quote today and discover why so many Gatineau businesses choose our services for their commercial junk removal needs."
      },
      {
        "slug": "renovation-debris-removal",
        "title": "Renovation and Construction Debris Removal",
        "description": "Removal of construction debris, demolition materials, old coverings, and job site waste. Fast intervention to keep your project on track.",
        "pageHeadline": "Renovation and Construction Debris Removal",
        "pageContent": "Renovation projects quickly generate a significant amount of debris and bulky materials. Our renovation and construction debris removal service is specially designed for contractors, renovators, and homeowners who need to quickly remove job site waste to keep their projects moving forward.\n\nWe remove all types of construction debris: drywall and plaster, framing lumber and moldings, doors and windows, kitchen cabinets, countertops, tiles and ceramics, carpet and subfloor, asphalt shingles, exterior siding, insulation, wiring and piping. Our team is familiar with construction materials and knows how to handle them safely.\n\nFor contractors and renovation teams, we offer flexible service that integrates with your project schedule. We can schedule regular pickups throughout your project or intervene as needed based on debris accumulation. Our quick response allows you to keep the site clean and safe.\n\nWe respect environmental standards by sorting recyclable materials like metal, untreated wood, and certain types of plastic. This responsible approach reduces the amount of debris sent to landfills while helping you meet your project's environmental requirements.\n\nOur trucks can access most residential and commercial sites in the Gatineau region. We offer competitive pricing based on volume and material type. For large projects, we can provide a detailed quote. Contact us to discuss your renovation project and discover how we can facilitate your job site."
      },
      {
        "slug": "estate-cleanout-services",
        "title": "Estate Cleanout and Liquidation Services",
        "description": "Complete and respectful service to empty a property following a death or liquidation. We treat each situation with compassion and professionalism.",
        "pageHeadline": "Estate Cleanout and Property Liquidation Services",
        "pageContent": "Emptying a house following a death or preparing a property for sale is an emotionally difficult task. Our estate cleanout service is offered with compassion, respect, and professionalism. We understand the sensitivity of these situations and work carefully to help you through this difficult stage.\n\nWe offer a complete property liquidation service that includes the removal of all belongings: furniture, clothing, dishes, books, decorations, electronics, garden items, and everything found in the residence. We can empty an entire house in a single day or work progressively according to your pace and emotional needs.\n\nOur approach is respectful and methodical. If you wish to keep certain objects or important documents, we take the time to sort with you before starting. We handle each item with care, aware that even ordinary objects can have special meaning. Our team is trained to work with empathy in these delicate circumstances.\n\nWe maximize the estate's value by identifying items that can be donated to charities, generating tax receipts for the estate. Furniture and objects in good condition are offered to families in need rather than simply being thrown away. This approach honors the memory of the deceased by giving their possessions a second life.\n\nWe often work in collaboration with notaries, estate executors, and real estate agents to coordinate the cleanout according to sale or property transfer timelines. Our services are available throughout the Gatineau region. Contact us to discuss your situation in complete confidentiality and receive respectful support during this difficult period."
      }
    ],
    "locations": [
      {
        "slug": "junk-removal-hull",
        "pageHeadline": "Junk Removal Service in Hull",
        "pageContent": "Hull is one of Gatineau's most dynamic sectors, with its established residential neighborhoods and downtown area undergoing transformation. Gatineau Junk Removal offers fast and reliable service to all Hull residents and businesses who need to remove unwanted items.\n\nWe know Hull's particularities well, from its century-old houses in Old Hull to modern condos near the Casino. Our trucks navigate easily through the narrow streets of the historic district, and we have the necessary experience to handle heavy objects in the narrow staircases typical of older buildings.\n\nWhether you're renovating a heritage property, moving from an apartment on Laurier Street, or liquidating an estate in the Wright-Champagne sector, our team responds quickly. We often offer same-day service for emergencies, and our prices remain among the most competitive in the region.\n\nOur commitment to recycling and donation directly benefits the Hull community. Items in good condition are donated to local organizations that help families in the sector. Contact us now for professional junk removal service in Hull."
      },
      {
        "slug": "junk-removal-aylmer",
        "pageHeadline": "Junk Removal Service in Aylmer",
        "pageContent": "Aylmer combines the charm of a historic village with modern residential developments, creating a diverse community that extends from Old Aylmer to new neighborhoods. Gatineau Junk Removal proudly serves the entire Aylmer area with junk removal service adapted to this sector's unique needs.\n\nWe work in all Aylmer neighborhoods, from luxurious waterfront properties along the Ottawa River to family homes in the Plateau, Champlain, and Wychwood developments. Our team knows the sometimes difficult access of certain properties and we're equipped to handle all types of situations.\n\nAylmer residents appreciate our quick response and environmentally responsible approach. Whether you need to remove old patio furniture before winter, clear a garage filled with sports equipment, or clean out an entire property, we offer courteous and efficient service at transparent prices.\n\nAvailable seven days a week, we can often respond the same day you call. Our knowledge of the Aylmer sector allows us to plan our travels efficiently and offer you fast service. Call us today to discover why so many Aylmer residents trust us."
      },
      {
        "slug": "junk-removal-gatineau",
        "pageHeadline": "Junk Removal Service in Gatineau Sector",
        "pageContent": "The Gatineau sector, with its established neighborhoods and busy commercial arteries, represents the heart of our city. Gatineau Junk Removal is proud to offer local junk removal service to all residents and businesses in this dynamic sector.\n\nFrom Maloney Boulevard to the Pointe-Gatineau sector, through the residential neighborhoods around Hospital Boulevard, we know every corner of the Gatineau sector. Our team responds quickly in single-family homes, apartment buildings, and local businesses that need to remove unwanted items.\n\nWe understand the particular challenges of the Gatineau sector: limited parking in some neighborhoods, access to upper floors of multiplexes, and high volume of junk removal during moving periods. Our local experience allows us to handle these situations efficiently while respecting your property and neighbors.\n\nOur service adapts to your needs, whether it's a simple pickup of a few items or a complete property cleanout. We offer transparent prices established on-site and work quickly to minimize inconvenience. Contact Gatineau Junk Removal now for professional service in your sector."
      },
      {
        "slug": "junk-removal-buckingham",
        "pageHeadline": "Junk Removal Service in Buckingham",
        "pageContent": "Buckingham, with its distinct character and strong community identity, deserves junk removal service that understands its particularities. Gatineau Junk Removal offers reliable and fast service to all Buckingham residents and surrounding areas.\n\nWe serve the entire Buckingham sector, from the historic downtown to expanding residential neighborhoods. Our team knows the country roads and private driveways that lead to many properties in the sector well. We're equipped to access more isolated residences and large properties.\n\nBuckingham homeowners often accumulate seasonal equipment, farm or landscaping materials, and bulky objects in their garages and sheds. Our junk removal service is perfect for freeing up these spaces and allowing you to better enjoy your property. We remove everything from old furniture to heavy equipment.\n\nOur commitment to fast service means we can often respond within 24 hours of your call. Our prices remain competitive despite the distance, and we always offer a free on-site assessment. Trust a local team that knows Buckingham and cares about your satisfaction."
      },
      {
        "slug": "junk-removal-masson-angers",
        "pageHeadline": "Junk Removal Service in Masson-Angers",
        "pageContent": "Masson-Angers is a growing sector that combines established neighborhoods with new residential developments. Gatineau Junk Removal is proud to offer professional junk removal service to the entire Masson-Angers community.\n\nWe work in all Masson-Angers neighborhoods, from waterfront properties along the Ottawa River to new housing developments. Our team understands the needs of young families settling in the sector as well as long-time residents who want to declutter their spaces.\n\nWhether you need to remove old furniture during a move, empty a basement filled with accumulated items, or clear renovation debris, we offer fast and courteous service. Our environmentally responsible approach means we recycle and donate as much as possible rather than sending everything to the landfill.\n\nAvailable seven days a week, we offer schedule flexibility that suits busy Masson-Angers families. Our prices are transparent and established on-site after volume assessment. Contact us today for junk removal service that respects your time and budget."
      },
      {
        "slug": "junk-removal-val-des-monts",
        "pageHeadline": "Junk Removal Service in Val-des-Monts",
        "pageContent": "Val-des-Monts, with its beautiful lakes and spacious properties, presents unique challenges for junk removal. Gatineau Junk Removal offers service adapted to the particular needs of this rural municipality located near Gatineau.\n\nWe serve all sectors of Val-des-Monts, including Perkins, Saint-Pierre-de-Wakefield, and the many hamlets scattered throughout the municipality. Our team is accustomed to navigating country roads and accessing properties set back from main roads.\n\nVal-des-Monts residents often have cottages, garages, and sheds filled with seasonal equipment, old furniture, and objects accumulated over the years. Our junk removal service helps you free up these valuable spaces. We remove all types of unwanted items, from appliances to construction materials, patio furniture to boating equipment.\n\nDespite the distance, we offer competitive rates and fast service. We plan our trips to Val-des-Monts efficiently to offer you the best possible price. Our commitment to recycling and donation applies to items we collect in your sector as well. Call us to discuss your junk removal needs in Val-des-Monts."
      },
      {
        "slug": "junk-removal-chelsea",
        "pageHeadline": "Junk Removal Service in Chelsea",
        "pageContent": "Chelsea is known for its beautiful wooded properties and proximity to Gatineau Park. Gatineau Junk Removal offers environmentally responsible junk removal service that aligns with the ecological values of this unique community.\n\nWe serve all sectors of Chelsea, from the main village to properties located on Old Chelsea, Kingsmere, and Scott roads. Our team has the necessary experience to navigate winding roads and access sloped or forested properties.\n\nChelsea residents particularly appreciate our commitment to recycling and reuse. We carefully sort all collected items to maximize recycling and donation. This responsible approach reduces our environmental impact while helping local organizations.\n\nWhether you're renovating a heritage property, moving from a family home, or clearing out a cottage, our service adapts to your needs. We offer flexible schedules and can often respond quickly. Our transparent prices and courteous service make us the preferred choice of Chelsea residents for their junk removal needs."
      },
      {
        "slug": "junk-removal-cantley",
        "pageHeadline": "Junk Removal Service in Cantley",
        "pageContent": "Cantley, with its unique combination of rural living and urban proximity, attracts many families who appreciate space and nature. Gatineau Junk Removal offers junk removal service adapted to the specific needs of this growing municipality.\n\nWe work in all sectors of Cantley, from residential neighborhoods near Montée de la Source to more isolated properties along rural roads. Our team knows Cantley's access particularities well and we're equipped to handle properties with long driveways or sloped terrain.\n\nCantley homeowners often benefit from large lots with garages, sheds, and storage spaces that can quickly become cluttered. Our junk removal service helps you reclaim these valuable spaces by efficiently removing all your unwanted items, from old furniture to garden equipment and construction materials.\n\nWe offer fast service with same-day response possible in many cases. Our prices are established transparently on-site, based on actual volume. Our environmentally responsible approach ensures recoverable items are recycled or donated rather than thrown away. Contact us today for professional junk removal service in Cantley."
      },
      {
        "slug": "junk-removal-la-peche",
        "pageHeadline": "Junk Removal Service in La Pêche",
        "pageContent": "La Pêche is a vast rural municipality spanning a large territory including several villages and hamlets. Gatineau Junk Removal offers reliable junk removal service throughout La Pêche municipality, regardless of your location.\n\nWe work in all sectors of La Pêche, including Wakefield, Alcove, Rupert, Brennan's Hill, and the many properties scattered throughout the municipality. Our team is accustomed to country roads and sometimes difficult access typical of this rural region.\n\nLa Pêche properties are often spacious with several outbuildings where objects accumulate over the years. Whether you need to empty a barn, garage, shed, or entire house, our team has the experience and equipment necessary to accomplish the job efficiently.\n\nDespite the distance and access particularities, we offer competitive rates and professional service. We plan our trips to La Pêche to optimize costs while offering you fast service. Our commitment to recycling and donation extends to all sectors we serve. Call us to discuss your junk removal project in La Pêche."
      },
      {
        "slug": "junk-removal-templeton",
        "pageHeadline": "Junk Removal Service in Templeton",
        "pageContent": "Templeton is a dynamic sector of Gatineau that combines established residential neighborhoods with developing commercial zones. Gatineau Junk Removal offers complete junk removal service to Templeton residents and businesses.\n\nWe know all Templeton neighborhoods well, from the sector near Montée Paiement to residential developments around Boulevard des Allumettières. Our team navigates easily in this sector and can respond quickly for all your junk removal needs.\n\nTempleton residents appreciate our fast service and transparent prices. Whether you're moving, renovating, or simply decluttering your home, we offer an efficient solution to remove all your unwanted items. We remove furniture, appliances, mattresses, sports equipment, and all other types of junk.\n\nFor Templeton businesses, we also offer service adapted to business hours with possible evening or weekend intervention. Our professional and discreet approach respects your operations while efficiently removing your commercial junk. Contact us now for professional junk removal service in Templeton."
      },
      {
        "slug": "junk-removal-pointe-gatineau",
        "pageHeadline": "Junk Removal Service in Pointe-Gatineau",
        "pageContent": "Pointe-Gatineau is a historic sector of Gatineau with a strong community identity and well-established residential neighborhoods. Gatineau Junk Removal is proud to offer local junk removal service that meets the specific needs of this sector.\n\nWe serve all Pointe-Gatineau neighborhoods, from streets near the Ottawa River to residential sectors around Boulevard Saint-René. Our team knows the sector's particularities well, including narrow streets and houses with exterior staircases typical of certain neighborhoods.\n\nPointe-Gatineau residents have access to fast and reliable junk removal service for all their needs. Whether you have furniture to remove, a basement to empty, or an estate to liquidate, our team responds with professionalism and respect. We handle your belongings with care and clean up after our work.\n\nOur commitment to the community is reflected in our recycling and donation approach. Items in good condition are offered to local organizations that help Pointe-Gatineau families and surrounding areas. Our prices are among the most competitive in the region, and we often offer same-day service. Call us to discover why so many Pointe-Gatineau residents trust us."
      },
      {
        "slug": "junk-removal-limbour",
        "pageHeadline": "Junk Removal Service in Limbour",
        "pageContent": "Limbour is a peaceful sector of Gatineau that offers a quiet living environment with beautiful properties. Gatineau Junk Removal is happy to offer professional junk removal service to Limbour residents and surrounding areas.\n\nWe know the Limbour sector and its particularities well. Our team is accustomed to navigating this sector and can easily access different properties, whether they're located near main arteries or on more secluded roads.\n\nLimbour homeowners appreciate our personalized service and respectful approach. Whether you need to remove a few items or empty an entire property, we offer the same level of professionalism and attention. Our team works efficiently while respecting your property and peace.\n\nWe offer flexible schedules that adapt to your availability, including evenings and weekends. Our prices are established transparently on-site, with no hidden fees or surprises. Our commitment to recycling and donation ensures your items are treated responsibly. Contact Gatineau Junk Removal today for courteous and efficient junk removal service in Limbour."
      }
    ]
  }
};

export function langContent(lang: Lang): PerLangContent | undefined {
  return siteConfig[lang];
}

export function availableLangs(): Lang[] {
  const langs: Lang[] = [];
  if (siteConfig.primaryLang) langs.push(siteConfig.primaryLang);
  if (siteConfig.secondaryLang && !langs.includes(siteConfig.secondaryLang)) langs.push(siteConfig.secondaryLang);
  return langs;
}
